const Colors = {
    background: '#333',
    background_blank: '#000',
    background_dark: '#111',
    background_item: '#222',
    background_selected_item: '#542100',
    background_existing_item: '#0a5100',
    background_submenu: '#444',
    background_shadow: 'rgba(0, 0, 0, 0.92)',
    border_submenu: '#111',
    border_submenu_text: '#777',
    border_item: '#555',
    border_container: '#333',
    search_underlay: '#444',
    text: '#EFEFEF',
    text_light: '#fff',
    text_dark: '#aaa',
    text_link: 'lightblue',
    text_description: '#444',
    background_button: '#aaa',
    background_details_button: '#222',
    background_action_button: '#444',
    border_action_button: '#000',
    photo_background: 'transparent', // '#000000',
    icon: '#777',
    tool_text: '#777',
    seek_tracker: '#777',
    transparent: 'rgba(0,0,0,0)',
    bars_icon: '#aaa',
    activity_indicator: '#444',
    seperator_playlists: '#444',
    background_playlists: '#000',
    background_search_results: '#000',
    border_search_results: '#444',
}

export default Colors