export const SERVICE_PENDING = 'service_pending'
export const SERVICE_ERROR = 'service_error'
export const SERVICE_SUCCESS = 'service_success'

export const SELECT_GENRE = 'SELECT_GENRE'
export const SELECT_RESULT = 'SELECT_RESULT'
export const SELECT_PLAYLIST_ITEM = 'SELECT_PLAYLIST_ITEM'
export const SELECT_PLAYLISTS_ITEM = 'SELECT_PLAYLISTS_ITEM'

export const SHOW_HOME = 'SHOW_HOME'
export const SHOW_GENRES = 'SHOW_GENRES'
export const SHOW_PLAYLIST = 'SHOW_PLAYLIST'
export const SHOW_PLAYLISTS = 'SHOW_PLAYLISTS'
export const SHOW_SEARCH_RESULTS = 'SHOW_SEARCH_RESULTS'
export const SHOW_RESULTS = 'SHOW_RESULTS'
export const SHOW_MOODS = 'SHOW_MOODS'
export const SHOW_SETTINGS = 'SHOW_SETTINGS'
export const SHOW_ARRANGABLE_PLAYLIST = 'SHOW_ARRANGABLE_PLAYLIST'

export const TOGGLE_PLAYLIST_SUBMENU = 'TOGGLE_PLAYLIST_SUBMENU'
export const HIDE_PLAYLIST_SUBMENU = 'HIDE_PLAYLIST_SUBMENU'

export const PLAY_NEXT = 'PLAY_NEXT'
export const PLAY_PREVIOUS = 'PLAY_PREVIOUS'

export const BUFF_PLAYLIST = 'BUFF_PLAYLIST'
export const PLAYLIST_CHANGED = 'PLAYLIST_CHANGED'
export const REMOVE_PLAYLIST_ITEM = 'REMOVE_PLAYLIST_ITEM'
export const MOVE_UP_PLAYLIST_ITEM = 'MOVE_UP_PLAYLIST_ITEM'
export const MOVE_DOWN_PLAYLIST_ITEM = 'MOVE_DOWN_PLAYLIST_ITEM'
export const QUEUE_NEXT_PLAYLIST_ITEM = 'QUEUE_NEXT_PLAYLIST_ITEM'
export const TOGGLE_FAVORITE_ITEM = 'TOGGLE_FAVORITE_ITEM'

export const PLAYLISTS_CHANGED = 'PLAYLISTS_CHANGED'
export const REMOVE_PLAYLISTS_ITEM = 'REMOVE_PLAYLISTS_ITEM'
export const VIEW_PLAYLISTS_ITEM = 'VIEW_PLAYLISTS_ITEM'

export const SAVE_PLAYLIST = 'SAVE_PLAYLIST'
export const RESTORE_PLAYLISTS = 'RESTORE_PLAYLISTS'
export const SHUFFLE_PLAYLIST = 'SHUFFLE_PLAYLIST'
export const CLEAR_PLAYLIST = 'CLEAR_PLAYLIST'
export const IMPORT_PLAYLIST = 'IMPORT_PLAYLIST'

export const RESTORE_STATES = 'RESTORE_STATES'

export const ADD_VIDEO_RECOMMENDATION = 'ADD_VIDEO_RECOMMENDATION'
export const RECOMMEND_MOOD = 'RECOMMEND_MOOD'
export const RECOMMEND_ERROR = 'RECOMMEND_ERROR'

export const SET_FULLSCREEN_ON_LENDSCAPE = 'SET_FULLSCREEN_ON_LENDSCAPE'
export const SET_USER_LARGE_PLAYER = 'SET_USER_LARGE_PLAYER'
export const SET_AUTO_BUFF_UP = 'SET_AUTO_BUFF_UP'
export const SET_THEME = 'SET_THEME'

export const REMOVE_ALL_NEXT = 'REMOVE_ALL_NEXT'
export const NETWORK_STATUS = 'NETWORK_STATUS'